[build]
  publish = "src"
  command = "npm run build"

[[redirects]]
  from = "/search/*"
  to = "https://openapi.naver.com/v1/search/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-Naver-Client-Id = "CLIENT_ID"
    X-Naver-Client-Secret = "CLIENT_SECRET"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200