[build]
  publish = "src"
  command = "npm run build"

[[redirects]]
  from = "/api/searchBlog*"
  to = "https://openapi.naver.com/v1/search/:splat"
  status = 200
  force = true
  [redirects.headers]
    X-Naver-Client-Id = "${CLIENT_ID}"
    X-Naver-Client-Secret = "${CLIENT_SECRET}"
